### ISSUE TITLE
MedicationList fails when country in MTP has nullflavor

### ISSUE THREAD

**Issue by oliveregger** [ahdis/ch-emed-pmp#22]
MedicaitonLIst fails PMP with the following:

 "statusText": "OK",
  "url": "https://test.ahdis.ch/mag-pmp/camel/xdsretrieve?uniqueId=urn:uuid:ff43d5ac-2223-4101-b63b-01cd931d6d3c&repositoryUniqueId=2.999.756.42.1",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://test.ahdis.ch/mag-pmp/camel/xdsretrieve?uniqueId=urn:uuid:ff43d5ac-2223-4101-b63b-01cd931d6d3c&repositoryUniqueId=2.999.756.42.1: 400 OK",
  "error": "There was an internal error while retrieving the document"

The assingedAuthor has a nuffFlavor for country, this could be the issue for the error afterwards:

<author>
    <templateId root="2.16.756.5.30.1.1.10.9.23"/>
    <time value="20220915045658.879-0400"/>
    <assignedAuthor>
      <id root="2.51.1.3" extension="7601000234438"/>
      <addr>
        <country nullFlavor="NI"/>
        <city>Zürich</city>
        <postalCode>8005</postalCode>
        <streetAddressLine>Krankenstrasse 2</streetAddressLine>
      </addr>
      <assignedPerson>
        <name>
          <family>Müller</family>
          <given>Alexander</given>
        </name>
      </assignedPerson>
    </assignedAuthor>
  </author>

rg.husky.emed.ch.errors.InvalidEmedContentException: Schematron error: {[[Text@0x144338fb: content=[dtr1-1-BIN: there must be a nullFlavor, or content must be non-empty]]; fpi=null; icon=null; lang=null; see=null; space=null]} in {/hl7:ClinicalDocument/hl7:component/hl7:structuredBody/hl7:component/hl7:section/hl7:entry/hl7:substanceAdministration/hl7:author/hl7:assignedAuthor/hl7:addr/hl7:country}
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validateAgainstSchematron(CdaChEmedValidator.java:300)
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validate(CdaChEmedValidator.java:265)
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validate(CdaChEmedValidator.java:239)
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validate(CdaChEmedValidator.java:206)
	at ch.qligier.hug.pmp.emed.ondemand.OnDemandMedicationListAssembler.assemble(OnDemandMedicationListAssembler.java:120)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generateOnDemandMedicationListDocument(GenerateOdDocumentCoprocessor.java:120)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:131)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
2022-09-15 09:52:52.532 ERROR [io-8080-exec-10] nDemandMedicationListAssembler: Validation error of a generated PML
org.husky.emed.ch.errors.InvalidEmedContentException: Schematron error: {[[Text@0x144338fb: content=[dtr1-1-BIN: there must be a nullFlavor, or content must be non-empty]]; fpi=null; icon=null; lang=null; see=null; space=null]} in {/hl7:ClinicalDocument/hl7:component/hl7:structuredBody/hl7:component/hl7:section/hl7:entry/hl7:substanceAdministration/hl7:author/hl7:assignedAuthor/hl7:addr/hl7:country}
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validateAgainstSchematron(CdaChEmedValidator.java:300)
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validate(CdaChEmedValidator.java:265)
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validate(CdaChEmedValidator.java:239)
	at org.husky.emed.ch.cda.validation.CdaChEmedValidator.validate(CdaChEmedValidator.java:206)
	at ch.qligier.hug.pmp.emed.ondemand.OnDemandMedicationListAssembler.assemble(OnDemandMedicationListAssembler.java:120)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generateOnDemandMedicationListDocument(GenerateOdDocumentCoprocessor.java:120)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:131)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
2022-09-15 09:52:52.532 ERROR [io-8080-exec-10] p.r.RetrieveDocumentsProcessor: There was an exception while retrieving a document
ch.qligier.hug.pmp.commons.errors.exceptions.InvalidDocumentException: The generation medication list is invalid
	at ch.qligier.hug.pmp.emed.ondemand.OnDemandMedicationListAssembler.assemble(OnDemandMedicationListAssembler.java:124)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generateOnDemandMedicationListDocument(GenerateOdDocumentCoprocessor.java:120)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:131)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:108)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:81)
	at org.apache.camel.management.DefaultInstrumentationProcessor.process(DefaultInstrumentationProcessor.java:90)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:812)
Wrapped by: ch.qligier.hug.pmp.commons.errors.exceptions.PmpInternalException: The On-Demand Document generation has failed
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generateOnDemandMedicationListDocument(GenerateOdDocumentCoprocessor.java:122)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:131)
	at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:108)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:81)
	at org.apache.camel.management.DefaultInstrumentationProcessor.process(DefaultInstrumentationProcessor.java:90)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:812)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:720)

**Comment by qligier** [comment]
Closing because it was about CDA documents.
