### ISSUE TITLE
400 Bad Request when retrieving the medication card (AmountQuantity: Invalid code in quantity)

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#26]
Getting a 400 Bad Request when retrieving the medication card for
MAGMED001
Trong Sang NEFF-WINGEIER, 1987-10-08 
Community ID = e7963774-9098-445f-9cab-5d52234b52c3

This is the patient Oliver setup with 1 MTP. Reading the card was working.

Now we add 2 MTPs and not it returns the error below.

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Header>
		<Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RetrieveDocumentSetResponse</Action>
		<MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:04011308-76f1-4719-a951-dcef2557e199</MessageID>
		<To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To>
		<RelatesTo xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:f437cc73-4d26-496a-ad4f-661d587efe82</RelatesTo>
	</soap:Header>
	<soap:Body>
		<ns2:RetrieveDocumentSetResponse xmlns:ns7="urn:ihe:iti:rmd:2017" xmlns:ns6="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns2="urn:ihe:iti:xds-b:2007">
			<ns4:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
				<ns4:RegistryErrorList>
					<ns4:RegistryError codeContext="An unexpected exception occurred" errorCode="XDSRegistryError" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
				</ns4:RegistryErrorList>
			</ns4:RegistryResponse>
		</ns2:RetrieveDocumentSetResponse>
	</soap:Body>
</soap:Envelope>

**Comment by arhuberg** [comment]
Maybe related to this (copied from https://pmp.posttenebrassilico.ch/pmp/mhd/logs)?
[2023-01-12 18:09:03] [info] java.lang.IllegalArgumentException: AmountQuantity: Invalid code in quantity
[2023-01-12 18:09:03] [info]   at org.projecthusky.fhir.emed.ch.epr.model.common.AmountQuantity.fromQuantity(AmountQuantity.java:53)
[2023-01-12 18:09:03] [info]   at org.projecthusky.fhir.emed.ch.epr.model.common.Dose.fromQuantityAndRange(Dose.java:53)
[2023-01-12 18:09:03] [info]   at org.projecthusky.fhir.emed.ch.epr.datatypes.ChEmedEprDosage.resolveDose(ChEmedEprDosage.java:101)
[2023-01-12 18:09:03] [info]   at org.projecthusky.fhir.emed.ch.epr.model.common.EffectiveDosageInstructions.lambda$fromDosages$1(EffectiveDosageInstructions.java:94)
[2023-01-12 18:09:03] [info]   at org.projecthusky.fhir.emed.ch.epr.model.common.EffectiveDosageInstructions.fromDosages(EffectiveDosageInstructions.java:106)
[2023-01-12 18:09:03] [info]   at org.projecthusky.fhir.emed.ch.epr.resource.ChEmedEprMedicationStatement.resolveEffectiveDosageInstructions(ChEmedEprMedicationStatement.java:289)
[2023-01-12 18:09:03] [info]   at org.projecthusky.fhir.emed.ch.epr.narrative.html.HtmlNarrativeGenerator.generate(HtmlNarrativeGenerator.java:67)
[2023-01-12 18:09:03] [info]   at ch.qligier.hug.pmp.emed.ondemand.PdfMedicationCardGenerator.generate(PdfMedicationCardGenerator.java:75)

**Comment by qligier** [comment]
Yes, it was still expecting the UCUM OID instead of its URI.

**Comment by qligier** [comment]
I've redeployed with a fix.

**Comment by arhuberg** [comment]
Tested Friday 13 Jan 2023 07017 EST 
Works as expected
