### ISSUE TITLE
ITI-68 Retrieving medication card fails with 400 error

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#35]
https://test.ahdis.ch/mag-pmp2/camel/xdsretrieve?uniqueId=urn:uuid:8a454731-b65d-4c25-82a3-755ab586a7ef&repositoryUniqueId=2.999.756.42.1
400 Bad Request: "An unexpected exception occurred"

1/18/2023, 11:12:46 AM	xds-iti43	SOAP → SOAP	POST	/pmp2/services/xds/iti43
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Header>
		<Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RetrieveDocumentSetResponse</Action>
		<MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:b9fff559-7180-4047-97b7-8e1c67628b89</MessageID>
		<To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To>
		<RelatesTo xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:96508406-577f-4ca7-8eab-69cf46904088</RelatesTo>
	</soap:Header>
	<soap:Body>
		<ns2:RetrieveDocumentSetResponse xmlns:ns7="urn:ihe:iti:rmd:2017" xmlns:ns6="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns2="urn:ihe:iti:xds-b:2007">
			<ns4:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure">
				<ns4:RegistryErrorList>
					<ns4:RegistryError codeContext="An unexpected exception occurred" errorCode="XDSRegistryError" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/>
				</ns4:RegistryErrorList>
			</ns4:RegistryResponse>
		</ns2:RetrieveDocumentSetResponse>
	</soap:Body>
</soap:Envelope>

https://pmp.posttenebrassilico.ch/pmp/mhd/logs
[2023-01-18 16:12:47] [info] 2023-01-18 16:12:47.217  INFO [read #3 - Delay] p.t.c.i.Iti43ResponseConverter: Uncaught exception while processing ITI-43 transaction
[2023-01-18 16:12:47] [info] org.projecthusky.fhir.emed.ch.common.error.InvalidEmedContentException: The practitioner is missing
[2023-01-18 16:12:47] [info]   at org.projecthusky.fhir.emed.ch.epr.resource.ChEmedEprPractitionerRole.resolvePractitioner(ChEmedEprPractitionerRole.java:40)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.AbstractFhirGenerator.prepareResource(AbstractFhirGenerator.java:169)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.FhirMedicationCardGenerator.addMedicationStatementFromMtp(FhirMedicationCardGenerator.java:166)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.FhirMedicationCardGenerator.processTreatment(FhirMedicationCardGenerator.java:105)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.OnDemandMedicationCardAssembler.assemble(OnDemandMedicationCardAssembler.java:166)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generatePmlcDocument(GenerateOdDocumentCoprocessor.java:205)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:149)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
[2023-01-18 16:12:47] [info] Wrapped by: ch.qligier.hug.pmp.common.errors.exceptions.PmpInternalException: The On-Demand Document generation has failed
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generatePmlcDocument(GenerateOdDocumentCoprocessor.java:207)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:149)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.ProcessorForAuthorizedRequest.process(ProcessorForAuthorizedRequest.java:26)
[2023-01-18 16:12:47] [info]   at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:108)
[2023-01-18 16:12:47] [info]   at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:81)
[2023-01-18 16:12:47] [info]   at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:812)
[2023-01-18 16:12:47] [info]   at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:720)
[2023-01-18 16:12:47] [info] 2023-01-18 16:12:47.218  INFO [read #3 - Delay] gier.hug.pmp.common.utils.Logs: Captured unexpected exception:
[2023-01-18 16:12:47] [info] org.projecthusky.fhir.emed.ch.common.error.InvalidEmedContentException: The practitioner is missing
[2023-01-18 16:12:47] [info]   at org.projecthusky.fhir.emed.ch.epr.resource.ChEmedEprPractitionerRole.resolvePractitioner(ChEmedEprPractitionerRole.java:40)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.AbstractFhirGenerator.prepareResource(AbstractFhirGenerator.java:169)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.FhirMedicationCardGenerator.addMedicationStatementFromMtp(FhirMedicationCardGenerator.java:166)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.FhirMedicationCardGenerator.processTreatment(FhirMedicationCardGenerator.java:105)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.emed.ondemand.OnDemandMedicationCardAssembler.assemble(OnDemandMedicationCardAssembler.java:166)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generatePmlcDocument(GenerateOdDocumentCoprocessor.java:205)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:149)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
[2023-01-18 16:12:47] [info] Wrapped by: ch.qligier.hug.pmp.common.errors.exceptions.PmpInternalException: The On-Demand Document generation has failed
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.coprocessors.GenerateOdDocumentCoprocessor.generatePmlcDocument(GenerateOdDocumentCoprocessor.java:207)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.dispatchDocumentRetrieval(RetrieveDocumentsProcessor.java:149)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.retrieve.RetrieveDocumentsProcessor.process(RetrieveDocumentsProcessor.java:92)
[2023-01-18 16:12:47] [info]   at ch.qligier.hug.pmp.transactions.pmp.ProcessorForAuthorizedRequest.process(ProcessorForAuthorizedRequest.java:26)
[2023-01-18 16:12:47] [info]   at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:108)
[2023-01-18 16:12:47] [info]   at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:81)
[2023-01-18 16:12:47] [info]   at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:812)
[2023-01-18 16:12:47] [info]   at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:720)
[2023-01-18 16:12:47] [info] 2023-01-18 16:12:47.230 DEBUG [read #3 - Delay] p.t.c.i.Iti43ResponseConverter: Sending response: RetrievedDocumentSet(super=Response(status=FAILURE, errors=[ErrorInfo[codeContext=An unexpected exception occurred,customErrorCode=,errorCode=REGISTRY_ERROR,location=,severity=ERROR]]), documents=[])
[2023-01-18 16:12:47] [info] 2023-01-18 16:12:47.234  INFO [io-8080-exec-59] MemoryAuditMessageTransmission: Saving a new ATNA message

**Comment by arhuberg** [comment]
This can be observed on https://test.ahdis.ch/mag-pmp2/#/mag
CHUV001
BRUNO KAKOB Aegerter-Bischoff, 1983-11-23 

This occurs after MTP, followed by a PADV with Comment.

Generating a Medication List appears to work, but not the Medication Card.

**Comment by qligier** [comment]
I need to rework a bit of code to fix this one. It will take a few days I think.

**Comment by qligier** [comment]
I've deployed a fix, the PADVs should be deleted and re-added to fix their aggregation.

**Comment by arhuberg** [comment]
I think we are getting this error.

Transaction Details
Permanent URL
https://test.ahdis.ch/eprik-proxy-cara/index.html#/transaction/ecb05730-4c37-41ce-8e81-08f9a8571e29
Status
Success
Sequence ID
ecb05730-4c37-41ce-8e81-08f9a8571e29
Type
xds-iti43
Request Timestamp
1/25/2023, 9:49:11 AM
Response Timestamp
1/25/2023, 9:49:11 AM
Runtime
563 ms

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RetrieveDocumentSetResponse</Action><MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:db52faae-3a06-4056-85e4-fc86ed3b8e48</MessageID><To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To><RelatesTo xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:1d34364a-826d-46d6-96a5-2215e2093c7f</RelatesTo></soap:Header><soap:Body><ns2:RetrieveDocumentSetResponse xmlns:ns7="urn:ihe:iti:rmd:2017" xmlns:ns6="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:ns5="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns:ns4="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" xmlns:ns3="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:ns2="urn:ihe:iti:xds-b:2007"><ns4:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure"><ns4:RegistryErrorList><ns4:RegistryError codeContext="An unexpected exception occurred" errorCode="XDSRegistryError" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/></ns4:RegistryErrorList></ns4:RegistryResponse></ns2:RetrieveDocumentSetResponse></soap:Body></soap:Envelope>

**Comment by qligier** [comment]
I've modified some values in the database, it should work now!

**Comment by arhuberg** [comment]
Can you fix this patient?
https://test.ahdis.ch/eprik-proxy-cara/index.html#/transaction/c646634b-560a-48f6-bc78-25962777b0a2
Status
Success
Sequence ID
c646634b-560a-48f6-bc78-25962777b0a2
Type
xds-iti43
Request Timestamp
1/25/2023, 10:01:53 AM
Response Timestamp
1/25/2023, 10:01:54 AM

CHUV001
BRUNO KAKOB Aegerter-Bischoff, 1983-11-23

**Comment by arhuberg** [comment]
Nevermind, I used the MAG to delete the PADV.

**Comment by arhuberg** [comment]
Tested with CHUV001
Submitted a MTP, followed by PADV change, and then PADV comment. 
Medication Card was returned successfully.

**Comment by arhuberg** [comment]
Could you clean-up the documents  for...
 YANEK SOLAR WEBER-LEDERGERBER, 1991-05-29 
I would like to clean them up - I cannot delete the last 3 from the MAG.

Thanks,
Tony

**Comment by qligier** [comment]
I've deleted all eMedication documents for that patient (CHUV009).

**Comment by arhuberg** [comment]
This is working as expected.
