### ISSUE TITLE
Error when retrieving medication card

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#51]
Hi,

Getting an error retrieving a medication card for the following patient:
CHUV002
NABIHA KRAFT-BRUHIN, 1980-06-22 

The log appears to show an error with the route - but I cannot tell why it is bad.

"route": {
							"coding": [
								{
									"system": "urn:oid:urn:oid:0.4.0.127.0.16.1.1.2.1",
									"code": "20053000",
									"display": "Oral use"
								}
							]
						}

https://test.ahdis.ch/eprik-cara/index.html#/transaction/07e520ba-8786-48f8-b2c3-a19867a8d386

--uuid:73b0cc6d-0f6c-46d0-99e0-6cfefe989ac3
Content-Type: application/xop+xml; charset=UTF-8; type="application/soap+xml"
Content-Transfer-Encoding: binary
Content-ID: <root.message@cxf.apache.org>

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><Action xmlns="http://www.w3.org/2005/08/addressing">urn:ihe:iti:2007:RetrieveDocumentSetResponse</Action><MessageID xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:5448a5e4-96e1-406e-b61e-47c1bddf0be3</MessageID><To xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</To><RelatesTo xmlns="http://www.w3.org/2005/08/addressing">urn:uuid:d86a3cab-ad12-4d8f-a8a2-7a938c598a32</RelatesTo></soap:Header><soap:Body><xds:RetrieveDocumentSetResponse xmlns:rmd="urn:ihe:iti:rmd:2017" xmlns:lcm="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" xmlns="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:xds="urn:ihe:iti:xds-b:2007" xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"><rs:RegistryResponse status="urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure"><rs:RegistryErrorList><rs:RegistryError codeContext="An unexpected exception occurred (b443d38)" errorCode="XDSRegistryError" severity="urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error"/></rs:RegistryErrorList></rs:RegistryResponse></xds:RetrieveDocumentSetResponse></soap:Body></soap:Envelope>
--uuid:73b0cc6d-0f6c-46d0-99e0-6cfefe989ac3--

Caused by: org.projecthusky.fhir.emed.ch.common.error.InvalidEmedContentException: The route of administration is invalid.
	at org.projecthusky.fhir.emed.ch.epr.datatypes.ChEmedEprDosage.resolveRouteOfAdministration(ChEmedEprDosage.java:87)
	at org.projecthusky.fhir.emed.ch.epr.model.common.EffectiveDosageInstructions.fromDosages(EffectiveDosageInstructions.java:87)
	at org.projecthusky.fhir.emed.ch.epr.resource.ChEmedEprMedicationStatement.resolveEffectiveDosageInstructions(ChEmedEprMedicationStatement.java:274)
	at org.projecthusky.fhir.emed.ch.epr.narrative.html.HtmlNarrativeGenerator.generate(HtmlNarrativeGenerator.java:67)
	at ch.qligier.hug.pmp.emed.ondemand.PdfMedicationCardGenerator.generate(PdfMedicationCardGenerator.java:75)
	at ch.qligier.hug.pmp.emed.ondemand.OnDemandMedicationCardAssembler.assemble(OnDemandMedicationCardAssembler.java:179)
	at ch.qligier.hug.pmp.transaction.operation.retrieve.coprocessor.GenerateOdDocumentCoprocessor.generatePmlcDocument(GenerateOdDocumentCoprocessor.java:205)

**Comment by arhuberg** [comment]
I tried to delete the remaining MTPs from the MAG (https://test.ahdis.ch/mag-pmp2/#/mag), but the delete is not working for the last 3 MTPs for the patient.

**Comment by qligier** [comment]
The system is invalid: `urn:oid:urn:oid:0.4.0.127.0.16.1.1.2.1` (double URN-encoding)

**Comment by arhuberg** [comment]
Thanks. I just could not see it.

**Comment by arhuberg** [comment]
Hi,

Could you delete all the documents for the CHUV002 patient?

We are unable to determine the source of those documents - and they have the bad route system code.

Tony

**Comment by qligier** [comment]
Sure, it is done.

**Comment by arhuberg** [comment]
Thanks. This can be closed.
