### ISSUE TITLE
CARA's integration platform under maintenance

### ISSUE THREAD

**Issue by qligier** [ahdis/ch-emed-pmp#52]
CARA's integration platform is under maintenance, from the 27th at 7h55 until the 29th at 17h05 (CEST).

The aggregator will fail for new patients, and may fail for older patients when its identifier cache is emptied.

**Comment by arhuberg** [comment]
HI,

Just confirming the error we are seeing is related to the maintenance...

https://test.ahdis.ch/eprik-cara/index.html#/transaction/5bd8f83a-b651-43ee-b66a-5ac8bf96c21c

org.apache.cxf.transport.http.HTTPException: HTTP response '503: null' when communicating with http://test.ahdis.ch/eprik-cara/camel/cara/EPDSTS/services/SecurityTokenService
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1618)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1625)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1192)
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$3.run(AutomaticWorkQueueImpl.java:413)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$AWQThreadFactory$1.run(AutomaticWorkQueueImpl.java:346)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by oliveregger** [comment]
you see the status also here: https://epr.cara.int.post-ehealth.ch/

**Comment by qligier** [comment]
The aggregator's PIX and PDQ queries to the integration platform seem to be working fine with the new version.

**Comment by oliveregger** [comment]
we updated the mobile access gateway, but we are experiencing problems with login to HIN from the portal (sometimes) and from the mobile access gateway (always).

**Comment by oliveregger** [comment]
changes are linked here: https://ahdis.github.io/epr-integration-cara/ , they should not have an impact when using the Mobile Access Gateway.
