### ISSUE TITLE
Unable to generate medication card for CHUV010 (after export with bad GLN)

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#58]
The medication card was generated until I added one more MTP (30485b8b-e808-4eac-98e8-ca6904acf4cd) which triggered this error.

This is the EPRIK transaction: https://test.ahdis.ch/eprik-cara/index.html#/transaction/45143092-7d5b-42f4-a137-26c93ee74e37

	{
	  "headers": {
	    "normalizedNames": {},
	    "lazyUpdate": null
	  },
	  "status": 400,
	  "statusText": "Bad Request",
	  "url": "https://test.ahdis.ch/mag-pmp2/camel/xdsretrieve?uniqueId=urn:uuid:d76ee425-b0cf-4716-a798-efc8890f7e21&repositoryUniqueId=2.999.756.42.1",
	  "ok": false,
	  "name": "HttpErrorResponse",
	  "message": "Http failure response for https://test.ahdis.ch/mag-pmp2/camel/xdsretrieve?uniqueId=urn:uuid:d76ee425-b0cf-4716-a798-efc8890f7e21&repositoryUniqueId=2.999.756.42.1: 400 Bad Request",
	  "error": "An unexpected exception occurred (63fe2874)"
	}

Caused by: ch.qligier.hug.pmp.common.error.exception.InvalidDocumentException: The PMLC generator failed to produce a valid document
	at ch.qligier.hug.pmp.emed.ondemand.OnDemandMedicationCardAssembler.assemble(OnDemandMedicationCardAssembler.java:190)
	at ch.qligier.hug.pmp.transaction.operation.retrieve.coprocessor.GenerateOdDocumentCoprocessor.generatePmlcDocument(GenerateOdDocumentCoprocessor.java:205)
	... 98 common frames omitted

**Comment by arhuberg** [comment]
[mtp.zip](https://github.com/ahdis/ch-emed-pmp/files/11441643/mtp.zip)

**Comment by qligier** [comment]
It seems to be an issue with the GLN identifier:
```
[ERROR] [INVARIANT] Rule gln-length: 'GLN must be exactly 13 characters long' Failed  in Bundle.entry[0].resource.entry[7].resource.ofType(MedicationStatement).contained[2].ofType(MedicationStatement).identifier[0].value [733:35] from source InstanceValidator from messageId Rule gln-length: 'GLN must be exactly 13 characters long' Failed
[ERROR] [INVARIANT] Rule gln-modulus-10: 'GLN must pass the modulus 10 check - https://www.gs1.org/services/how-calculate-check-digit-manually' Failed  in Bundle.entry[0].resource.entry[7].resource.ofType(MedicationStatement).contained[2].ofType(MedicationStatement).identifier[0].value [733:35] from source InstanceValidator from messageId Rule gln-modulus-10: 'GLN must pass the modulus 10 check - https://www.gs1.org/services/how-calculate-check-digit-manually' Failed
[ERROR] [INVARIANT] Rule gln-startswith7601: 'GLN must start with 7601 for swiss hcp' Failed  in Bundle.entry[0].resource.entry[7].resource.ofType(MedicationStatement).contained[2].ofType(MedicationStatement).identifier[0].value [733:35] from source InstanceValidator from messageId Rule gln-startswith7601: 'GLN must start with 7601 for swiss hcp' Failed
```

That won't work:
```json
{
	"system": "urn:oid:2.51.1.3",
	"value": "AbCDefgH1111x"
}
```

**Comment by arhuberg** [comment]
OK - thanks. That is just bad test data.

Sorry I missed it in the log.

**Comment by qligier** [comment]
In the logs, the validation messages are dumped before the exception "The PMLC generator failed to produce a valid document".

Now I need to understand why the document was accepted, since it was invalid.

**Comment by arhuberg** [comment]
Should a bad GLN get rejected when the MTP/PADV is handled?

**Comment by qligier** [comment]
Sure, the same Practitioner definition applies (or should apply, since it was not the case) to all documents: https://build.fhir.org/ig/CARA-ch/ch-emed-epr/StructureDefinition-ch-emed-epr-practitioner.html
