### ISSUE TITLE
Validation service (https://test.ahdis.ch/matchboxv3/fhir/$validate) takes longer than expected

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#60]
We configure our test systems to validate documents using (https://test.ahdis.ch/matchboxv3/fhir/$validate) and record the results. This allows us to generate a report to determine that we are creating the MTP and PADV documents correctly.

We have our REST services configured to timeout after 10 seconds. This is normally ok for all CARA operations.

Our requests will detect the timeout and retry.

The $validate operation will timeout in the mornings (beginning of the day - at least it seems that way; maybe when there are delays between tests). I do not think this is an operational issue as clients will not have this option enabled in production - just wanted to report it.

This is the error on our side - just wanted you to see it (I know it does not really help).

Here is the approx time of the error: 2023-08-08 15:04:27.943 (UTC)

Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://test.ahdis.ch/matchboxv3/fhir/$validate": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
	at com.cerner.soarian.sc.ord.dao.chemedication.CHeMedicationHistoryDAOImpl.validateDocument_aroundBody10(CHeMedicationHistoryDAOImpl.java:202)

**Comment by oliveregger** [comment]
matchbox loads the ig dynamically for validation and discards it, if they are not in use after half an hour. loading up the ig's initially could take more then 10 seconds, therefore your behavior seems explainable.

matchbox allows to cache ig's forever, however on test system this is not activated.

**Comment by arhuberg** [comment]
Thanks for the explanation.

**Comment by arhuberg** [comment]
Our use of the validation api  (https://test.ahdis.ch/matchboxv3/fhir/$validate) is not intended for production (usually just dev, test, and maybe certification testing if needed) - so we are changing the timeout to 60 seconds for this operation only when it is enabled. I think this can be closed.
