### ISSUE TITLE
FHIR Validation tool fails with Caused by: java.io.IOException: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)

### ISSUE THREAD

**Issue by arhuberg** [ahdis/ch-emed-pmp#61]
I was trying to run the HAPI validator and got the error below.

We ran this a few months ago, but now it is failing.

org.hl7.fhir.validator-wrapper/releases/download/1.0.37/validator_cli.jar
args = ['-version', '4.0.1', '-profile', 'http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan', '-ig', 'ch.fhir.ig.ch-emed#current']

> Task :validateMtp
FHIR Validation tool Version 5.6.92 (Git# dc677cad51a2). Built 2023-01-20T22:59:09.486Z (201 days old)
  Java:   11.0.17 from C:\jdk-11.0.17 on amd64 (64bit). 8116MB available

WARNING: Default file encoding is windows-1252 which may cause unexpected results.
         To fix this issue, run this program with the parameter '-Dfile.encoding=UTF-8'
         Future releases may not be able to run at all with encoding windows-1252

  Paths:  Current = ch-emed-validator, Package Cache = \.fhir\packages
  Params: -version 4.0.1 -profile http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-document-medicationtreatmentplan -ig ch.fhir.ig.ch-emed#current mtp.json
  Jurisdiction: United States of America
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1Installing hl7.fhir.r4.core#4.0.1 to the package cache
  Fetching:
....................................................................................................
  Installing: .................................................................................................... done.
.:Installing hl7.fhir.xver-extensions#0.0.12 to the package cache
  Fetching:

  Installing:  done.
 - 4576 resources (00:43.016)
Installing hl7.terminology#5.2.0 to the package cache
  Fetching:
....................................................................................
  Installing: .................................................................................... done.
Installing hl7.fhir.uv.extensions.r4#1.0.0 to the package cache
  Fetching:
....................................
  Installing: .................................... done.
  Load hl7.fhir.uv.extensions.r4#1.0.0 - 1328 resources (00:12.985)
  Load hl7.terminology#5.2.0 - 4195 resources (00:01.103)
  Load R5 ExtensionsException in thread "main" org.hl7.fhir.exceptions.FHIRException: Unable to fetch: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:557)
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadFromCIBuild(FilesystemPackageCacheManager.java:577)
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:537)
        at org.hl7.fhir.r5.conformance.R5ExtensionsLoader.load(R5ExtensionsLoader.java:81)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:378)
        at org.hl7.fhir.validation.cli.services.ValidationService.initializeValidator(ValidationService.java:356)
        at org.hl7.fhir.validation.ValidatorCli.doValidation(ValidatorCli.java:283)
        at org.hl7.fhir.validation.ValidatorCli.main(ValidatorCli.java:138)
        at ServerKt.main(Server.kt:52)
Caused by: java.io.IOException: Invalid HTTP response 404 from http://build.fhir.org/hl7.fhir.r5.core.tgz (Not Found) (no content)
        at org.hl7.fhir.utilities.SimpleHTTPClient$HTTPResult.checkThrowException(SimpleHTTPClient.java:75)
        at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchFromUrlSpecific(FilesystemPackageCacheManager.java:551)
        ... 8 more

**Comment by oliveregger** [comment]
@arhuberg you need to update to the latest validator: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Downloadingthevalidator

**Comment by arhuberg** [comment]
Thanks

**Comment by arhuberg** [comment]
This can be closed.
